# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Train and Test AIs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  statuses: write
  checks: write
  contents: write
  pull-requests: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install AI's dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: install spacy
      run: | 
        python -m spacy download en_core_web_sm

    - name: Lint AI's with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test AIS with pytest
      run: |
        cd ./ner
        pytest *_test*.py --junitxml=report.xml -s

    - name: Test AI's Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: ./ner/report.xml   # Path to test results
        reporter: java-junit        # Format of test results

    - name: Install build dependencies
      if: success() || failure()    # run this step even if previous step failed
      with:
        run: python -m pip install -U setuptools wheel build

    - name: Build
      if: success() || failure()    # run this step even if previous step failed
      with:
        run: |
          python -m build .
